name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - tensorflow
  - keras
  - torch
  - flask
  - django
  - requests
  - beautifulsoup4
  - scrapy
  - sqlalchemy
  - pymongo
  - psycopg2
  - jupyterlab
  - pytest
  - black
  - flake8
  - opencv-python
  - pillow
  - nltk
  - spacy
  - pip:
    - <additional packages from requirements.txt>
